Remove future parser option
This avoids errors like:
Error: Could not parse application options: invalid option: --parser
Error: puppet syntax error in .... 
due to the fact that on current Puppet version the --parser option is no longer valid